server:
  port: 8081
  servlet:
    session:
      timeout: 10080m
  address: 0.0.0.0

spring:
  datasource:
    username: root
    password: 123456
#    password: Aa1412646546!
    url: jdbc:mysql://localhost:3306/community?useSSL=TRUE&useUnicode=TRUE&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.pigrz.pojo
  mapper-locations: classpath:mapper/*.xml
